### ISSUE TITLE
Add task for deploying all dependencies to the cluster

### ISSUE THREAD

**Issue by pehala** [Kuadrant/testsuite-pipelines#8]
This includes:
* Project sail operator + deployment
* Tools (Keycloak + Mockserver)
* Creates required namespaces
* Deploys Kuadrant from a specific catalog source
* Deploys all required secrets (AWS, GCP, lets-encrypt)
* Creates all required objects (ManagedZone, ClusterIssuer)

**Comment by martinhesko** [comment]
we split investigating the options between me and @averevki , we looked through bash/kustomize, helm and [free-deployer](https://gitlab.cee.redhat.com/3scale-qe/infra/free-deployer)

We concluded that we would open-source free-deployer and use it for our test dependency creation and turn @averevki's demo prototype into an image.

**Comment by martinhesko** [comment]
I compiled steps we need to take to deploy dependencies into free-deployer into https://github.com/Kuadrant/testsuite-pipelines/issues/10

closing this
